version: "3"

services:
  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - ./server:/server
      # - /home/ubuntu/addeliverynetwork/server/node_modules
      #ports:
      #- 80:3001

    command: npm run start
    env_file: ./server/.env
    depends_on:
      - db
    restart: unless-stopped
    tty: true
    links:
      - db
    networks:
      - webappnetwork

  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    command: mongod

    volumes:
      - data-node:/data/db
    networks:
      - webappnetwork

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - webappnetwork

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email webdeveloper.jones@gmail.com --agree-tos --no-eff-email --staging -d properlife.app  -d www.properlife.app

networks:
  webappnetwork:
    driver: bridge

volumes:
  data-node:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: root/NextGenPL/server/build/
      o: bind
