version: "3"

services:
  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - ./server:/server
      # - /home/ubuntu/addeliverynetwork/server/node_modules
    ports:
      - 80:3001

    command: npm run start
    env_file: ./server/.env
    depends_on:
      - db
    restart: unless-stopped
    tty: true
    links:
      - db
    networks:
      - webappnetwork

  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    command: mongod

    volumes:
      - data-node:/data/db
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge

volumes:
  data-node:
